
version: 2

models:
    - name: my_child_dbt_model
      description: "Inherited dbt model"
      group: platform
      access: public
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
              - unique

